In [2]:
import pandas as pd

df = pd.read_excel("HD_phaseGenes.xlsx", sheet_name="Table S2 - Phase C,D Gene Stats", header=26)

             Gene Phase D p-value Phase D effect Phase
51          ABCA8             0.0        7.37272     D
74          ABCC9             0.0       5.523023     D
560    AC005165.1             0.0       2.961955     D
1017   AC007091.1             0.0       6.530972     D
1308   AC008060.1             0.0       6.244598     D
...           ...             ...            ...   ...
37072        ZIC4             0.0       6.540266     D
37302      ZNF423             0.0       3.413034     D
37384      ZNF536             0.0       5.421753     D
37450      ZNF608             0.0         2.5012     D
37701      ZSCAN9             0.0        4.37378     D

[719 rows x 4 columns]

In [4]:
# phase D
phase_d = df[df["Phase"] == "D"]
display(phase_d[["Gene", "Phase D p-value", "Phase D effect", "Phase"]])
print(phase_d.Gene.to_list())

phase_d.to_csv("phase_d_genes.csv", index=False)

             Gene Phase D p-value Phase D effect Phase
51          ABCA8             0.0        7.37272     D
74          ABCC9             0.0       5.523023     D
560    AC005165.1             0.0       2.961955     D
1017   AC007091.1             0.0       6.530972     D
1308   AC008060.1             0.0       6.244598     D
...           ...             ...            ...   ...
37072        ZIC4             0.0       6.540266     D
37302      ZNF423             0.0       3.413034     D
37384      ZNF536             0.0       5.421753     D
37450      ZNF608             0.0         2.5012     D
37701      ZSCAN9             0.0        4.37378     D

[719 rows x 4 columns]

['ABCA8', 'ABCC9', 'AC005165.1', 'AC007091.1', 'AC008060.1', 'AC023886.1', 'AC027117.2', 'AC069120.1', 'AC069208.1', 'AC090502.1', 'AC090833.1', 'AC091940.1', 'AC092958.1', 'AC093330.2', 'AC093503.3', 'AC098829.1', 'AC104574.2', 'AC110023.1', 'AC110285.1', 'AC112206.2', 'AC243773.2', 'ACOT11', 'ACOT7', 'ACSBG1', 'ACSS1', 'ACTB', 'ACTG1', 'ADARB2', 'ADCY2', 'ADCY8', 'ADGRG1', 'ADRA1A', 'AEBP1', 'AHNAK', 'AL049874.3', 'AL136311.1', 'AL354809.1', 'AL359922.1', 'AL391807.1', 'AL445623.2', 'AL590094.1', 'AL590617.2', 'ALDH1A1', 'ALDH1L1', 'ALDOA', 'ALDOC', 'AMER2', 'AMOTL2', 'AMPD3', 'ANAPC11', 'ANGPT1', 'ANGPTL4', 'ANK1', 'ANKRD29', 'ANKRD44', 'ANO4', 'APOE', 'AQP1', 'ARHGAP23', 'ARHGAP24', 'ARHGAP42', 'ARHGEF40', 'ARL4C', 'ARL6IP1', 'ASPA', 'ATP1A2', 'ATP1B1', 'ATP2B4', 'ATP5D', 'ATP5E', 'ATP5H', 'ATP5I', 'ATP5J', 'ATP5J2', 'ATP5O', 'ATP6AP1', 'ATP6V0A1', 'ATP6V0B', 'ATP6V1F', 'ATP6V1G1', 'AURKAIP1', 'B2M', 'B4GAT1', 'BAG3', 'BANF1', 'BCAS1', 'BDH2', 'BEST1', 'BEX1', 'BEX3', 'BEX4', 'BMP7', 'BMPR1B', 'BTF3', 'BTG1', 'C10orf90', 'C12orf57', 'C14orf2', 'C14orf39', 'C19orf70', 'C1orf122', 'C1orf61', 'C1orf87', 'C3', 'C4orf22', 'C4orf48', 'CA2', 'CA8', 'CALCOCO2', 'CALM1', 'CALM2', 'CALR', 'CALY', 'CAMK2D', 'CAMK2N1', 'CARNS1', 'CBFB', 'CBR1', 'CBX8', 'CC2D2A', 'CCDC50', 'CCDC85B', 'CCT4', 'CD22', 'CD44', 'CD55', 'CD81', 'CD82', 'CDC42EP4', 'CDH13', 'CDH19', 'CDH20', 'CDK18', 'CDK2AP2', 'CDKN2A', 'CDKN2B', 'CDKN2B-AS1', 'CECR2', 'CERCAM', 'CFL2', 'CGNL1', 'CHCHD2', 'CHI3L1', 'CLDN11', 'CLDND1', 'CLMN', 'CLSPN', 'CLU', 'CNDP1', 'CNP', 'COBLL1', 'COL4A5', 'COLEC12', 'COPE', 'COPS9', 'COTL1', 'COX14', 'COX4I1', 'COX5B', 'COX6B1', 'COX6C', 'COX7A2', 'COX7B', 'COX7C', 'COX8A', 'CP', 'CPM', 'CRABP1', 'CREB5', 'CROCC', 'CRYAB', 'CSGALNACT1', 'CSRP1', 'CST3', 'CSTB', 'CTSD', 'CXXC5', 'CYBRD1', 'DAAM2', 'DCXR', 'DDR1', 'DDT', 'DNAH14', 'DNAJA1', 'DNAJB6', 'DOCK10', 'DOCK2', 'DOCK5', 'DPF3', 'DPYSL2', 'DRAP1', 'DUSP10', 'DYNLL1', 'ECH1', 'EDF1', 'EEF1A1', 'EEF1B2', 'EEF1D', 'EEF2', 'EFEMP1', 'EFHD1', 'EID1', 'EIF1', 'ELAVL2', 'ELOB', 'EMC10', 'EMX2OS', 'ENAH', 'ENO2', 'ENPP2', 'EPHX1', 'ERBB3', 'ERBIN', 'ETS1', 'EZR', 'FA2H', 'FAM107A', 'FAM107B', 'FAM189A2', 'FAM69C', 'FAU', 'FBXL7', 'FCHSD2', 'FERMT2', 'FGF1', 'FGFR1', 'FGFR2', 'FGFR3', 'FIGN', 'FIS1', 'FKBP2', 'FLJ12825', 'FOLH1', 'FOS', 'FOXD1', 'FRMPD2', 'FTH1', 'FTL', 'GAB1', 'GABARAP', 'GABARAPL2', 'GABRG1', 'GADD45B', 'GADD45GIP1', 'GALNT9', 'GAPDH', 'GDI1', 'GFAP', 'GLI2', 'GLIPR2', 'GLIS3', 'GLUL', 'GNAS', 'GNG2', 'GPRC5B', 'GPS2', 'GPX1', 'GPX4', 'GRAMD3', 'GREM1', 'GRIA4', 'GSN', 'GTF3C6', 'GUK1', 'H1FX', 'H2AFZ', 'H3F3B', 'HAND2-AS1', 'HEPACAM', 'HHIP', 'HIF3A', 'HINT1', 'HIP1R', 'HIPK2', 'HLA-A', 'HLA-C', 'HNRNPM', 'HOTAIRM1', 'HOXA-AS2', 'HOXA-AS3', 'HOXA13', 'HOXB-AS1', 'HOXB-AS3', 'HOXC10', 'HOXC4', 'HOXD-AS2', 'HOXD11', 'HPN-AS1', 'HPSE2', 'HSD17B11', 'HSP90AA1', 'HSP90AB1', 'HSPA1A', 'HSPA1B', 'HSPA5', 'HSPA8', 'HSPB1', 'HSPE1', 'IDS', 'IFITM3', 'IL13RA1', 'IP6K3', 'IRX5', 'ISCU', 'ITGA2', 'ITGA6', 'ITGB4', 'ITGB5', 'ITM2B', 'ITM2C', 'ITPKB', 'ITPR2', 'JSRP1', 'JUN', 'KANK1', 'KCNC2', 'KCNH8', 'KCNJ10', 'KCNJ3', 'KIAA1211', 'KIAA1755', 'KIF2A', 'KIRREL', 'KLF12', 'KLF15', 'LAMA2', 'LAMP2', 'LAMTOR4', 'LBX1-AS1', 'LDHB', 'LHFP', 'LHX1', 'LHX5', 'LHX5-AS1', 'LHX6', 'LHX9', 'LINC00320', 'LINC00499', 'LINC00639', 'LINC00682', 'LINC01138', 'LINC01170', 'LINC01608', 'LINC01792', 'LINC01977', 'LINC02381', 'LITAF', 'LPAR1', 'LRIG1', 'LRP10', 'LRP2', 'LRP2BP', 'LRP4', 'LRRC63', 'LTBP1', 'LUC7L3', 'MAGED2', 'MAL', 'MAML2', 'MAP4K4', 'MAPKAPK2', 'MAPT', 'MARCKS', 'MBP', 'MIR219A2', 'MLC1', 'MOBP', 'MOG', 'MRFAP1', 'MRPL20', 'MRVI1', 'MSC-AS1', 'MT-CO2', 'MT2A', 'MT3', 'MTCH1', 'MUM1', 'MYL6', 'MYO10', 'MYO1E', 'MYRF', 'MZT2B', 'NAB1', 'NACA', 'NACC2', 'NCKAP5', 'NCOR1', 'NDE1', 'NDRG1', 'NDRG2', 'NDUFA1', 'NDUFA2', 'NDUFA3', 'NDUFA4', 'NDUFAF3', 'NDUFB10', 'NDUFB7', 'NDUFB8', 'NDUFC1', 'NDUFS5', 'NEAT1', 'NEDD8', 'NENF', 'NEUROD2', 'NFIB', 'NFIX', 'NFKBIA', 'NGB', 'NINJ2', 'NKX2-5', 'NPY', 'NR2F1-AS1', 'NR4A2', 'NRN1', 'NUDC', 'NXPH1', 'OAF', 'OAZ1', 'ONECUT1', 'OPALIN', 'OST4', 'PADI2', 'PALM2', 'PANCR', 'PARP14', 'PARP8', 'PBXIP1', 'PCBP1', 'PCDH15', 'PCSK1N', 'PDE1A', 'PDZRN3', 'PEA15', 'PEBP1', 'PEX5L', 'PFDN5', 'PFKP', 'PFN1', 'PHLDB1', 'PHPT1', 'PHYHIPL', 'PIEZO2', 'PITX1', 'PLA2G16', 'PLA2G4A', 'PLCB4', 'PLEKHG1', 'PLEKHH1', 'PLOD2', 'PLP1', 'PLPP3', 'PLS3', 'PLSCR4', 'PLXNB1', 'PMP22', 'POLR2F', 'POLR2I', 'POLR2J', 'POLR2L', 'POU4F1', 'POU4F2', 'PPDPF', 'PPFIBP2', 'PPP3CB-AS1', 'PRDM13', 'PRDM16', 'PRDX1', 'PRDX2', 'PRDX5', 'PRELID1', 'PREX1', 'PREX2', 'PRKCA', 'PRNP', 'PROX1', 'PRR5L', 'PRUNE2', 'PSENEN', 'PSMA7', 'PSMC5', 'PTMA', 'PTPRC', 'PTPRK', 'PTPRZ1', 'QKI', 'RABAC1', 'RAC1', 'RACK1', 'RANBP3L', 'RASA3', 'RASGRP3', 'RASL12', 'RASSF2', 'RASSF4', 'RFTN2', 'RGCC', 'RGMA', 'RHBDD2', 'RHOB', 'RHOU', 'RN7SL2', 'RNF219-AS1', 'RNF220', 'RPL10', 'RPL10A', 'RPL11', 'RPL12', 'RPL13', 'RPL13A', 'RPL14', 'RPL15', 'RPL18', 'RPL18A', 'RPL19', 'RPL21', 'RPL22', 'RPL23A', 'RPL24', 'RPL26', 'RPL27', 'RPL28', 'RPL29', 'RPL3', 'RPL30', 'RPL32', 'RPL34', 'RPL35', 'RPL35A', 'RPL36', 'RPL36AL', 'RPL38', 'RPL39', 'RPL4', 'RPL41', 'RPL5', 'RPL6', 'RPL7', 'RPL7A', 'RPL8', 'RPL9', 'RPLP0', 'RPLP1', 'RPLP2', 'RPS11', 'RPS12', 'RPS13', 'RPS14', 'RPS15', 'RPS15A', 'RPS16', 'RPS17', 'RPS18', 'RPS19', 'RPS19BP1', 'RPS2', 'RPS21', 'RPS23', 'RPS24', 'RPS25', 'RPS26', 'RPS27', 'RPS27A', 'RPS28', 'RPS29', 'RPS3', 'RPS3A', 'RPS4X', 'RPS5', 'RPS6', 'RPS7', 'RPS8', 'RPS9', 'RPSA', 'RRBP1', 'RTL8C', 'SAMD4A', 'SAP18', 'SARAF', 'SBDS', 'SCAND1', 'SCD', 'SDC4', 'SDF4', 'SEC11C', 'SEC62', 'SELENOM', 'SELENOP', 'SELENOW', 'SEMA3B', 'SEPT10', 'SEPT7', 'SERF2', 'SERINC1', 'SFTA3', 'SH3BGRL3', 'SH3TC2', 'SHOX2', 'SHROOM4', 'SIX1', 'SKAP2', 'SLC14A1', 'SLC17A6', 'SLC17A7', 'SLC1A2', 'SLC1A3', 'SLC25A18', 'SLC25A5', 'SLC26A3', 'SLC39A12', 'SLC6A5', 'SLC7A11', 'SLCO1A2', 'SLCO1C1', 'SMIM26', 'SMIM29', 'SNHG6', 'SNRNP70', 'SNRPD2', 'SNTB1', 'SOD1', 'SORT1', 'SOX2', 'SOX5', 'SOX6', 'SOX9', 'SP100', 'SPAG6', 'SPP1', 'SRCIN1', 'SREBF1', 'SREBF2', 'SRP14', 'SSR4', 'SST', 'ST18', 'STAT5A', 'STK3', 'STMN1', 'STRAP', 'STRIP1', 'STUB1', 'SURF1', 'SVEP1', 'SYNJ2', 'SYNPO2', 'SYT17', 'SYTL4', 'TAL1', 'TBKBP1', 'TBR1', 'TBX5', 'TCEAL4', 'TCEAL6', 'TCEAL9', 'TCF25', 'TCF4', 'TCP11L2', 'TFAP2D', 'TGFBR2', 'TIMP2', 'TLE2', 'TLE3', 'TMA7', 'TMBIM6', 'TMEM108', 'TMEM130', 'TMEM144', 'TMEM160', 'TMEM165', 'TMEM235', 'TMEM258', 'TMEM41B', 'TMEM63A', 'TMEM98', 'TMSB10', 'TMSB4X', 'TMTC2', 'TNS1', 'TOMM20', 'TOX', 'TPI1', 'TRIM2', 'TRMT112', 'TSC22D4', 'TSPYL1', 'TSPYL2', 'TTLL7', 'TTYH2', 'TUBA1A', 'TUBA1B', 'TUBB2A', 'TUBB4B', 'TWIST1', 'UBA52', 'UBB', 'UBC', 'UBL5', 'UCHL1', 'UGT8', 'UQCR10', 'UQCRQ', 'USMG5', 'USP54', 'VAMP2', 'VCAN', 'VEGFB', 'VRK2', 'WBP2', 'WDR83OS', 'YPEL3', 'ZBTB16', 'ZC3HAV1', 'ZFP36L1', 'ZIC1', 'ZIC4', 'ZNF423', 'ZNF536', 'ZNF608', 'ZSCAN9']